### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by qingweiSun** [appetizerio/insights.py#10]
Node.js is not installed and some functionality might not work properly
valid access token
not a valid APK

Node.js   已经安装了

**Comment by qingweiSun** [comment]
python insights.py process D:\AndroidProjects\AS_jjb\app\build\outputs\apk\5.6.30-debug.apk D:\AndroidProjects\AS_jjb\app\build\outputs\apk\5.6.30-debug_s.apk

**Comment by mingyuan-xia** [comment]
命令行是否可以执行node

**Comment by qingweiSun** [comment]
可以

C:\Users\Administrator>node
> hello word
hello word
      ^^^^

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Mingyuan Xia <notifications@github.com>
发送时间: Wednesday, June 20, 2018 4:54:47 PM
收件人: appetizerio/insights.py
抄送: qingweiSun; Author
主题: Re: [appetizerio/insights.py] 问题 (#10)


命令行是否可以执行node

―

**Comment by qingweiSun** [comment]
解决了,居然是重启电脑

**Comment by mingyuan-xia** [comment]
可能是你安装完node没有关闭旧的命令行

**Comment by qingweiSun** [comment]
请问python  插装的包像带上悬浮窗该执行什么命令呢

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Mingyuan Xia <notifications@github.com>
发送时间: Wednesday, June 20, 2018 5:12:44 PM
收件人: appetizerio/insights.py
抄送: qingweiSun; State change
主题: Re: [appetizerio/insights.py] 问题 (#10)


可能是你安装完node没有关闭旧的命令行

―

**Comment by mingyuan-xia** [comment]
--enable-inapp-menu
-h里面有
