### ISSUE TITLE
小米手机如何授权

### ISSUE THREAD

**Issue by HakunamatataLeo** [appetizerio/insights.py#12]
![image](https://user-images.githubusercontent.com/4550421/59666585-af896200-91e7-11e9-9e56-dd3b71468a9a.png)

**Comment by mingyuan-xia** [comment]
运行时通知栏有信息收集到数据么

**Comment by HakunamatataLeo** [comment]
并没有

**Comment by mingyuan-xia** [comment]
具体点呢
没有通知栏还是通知栏显示没有收集到数据
没有通知栏->运行的不是插桩包
没收集到数据 -> Android<4.4 APP没有申明EXTERNAL_STORAGE权限，Android >5不应该出现

**Comment by HakunamatataLeo** [comment]
提示：没有通知栏->运行的不是插桩包
python insights.py 生成的包

**Comment by mingyuan-xia** [comment]
+QQ群 467889502
