### ISSUE TITLE
modify DEVICE_LOG_BASE in insights.py doesn't work

### ISSUE THREAD

**Issue by Ernest-su** [appetizerio/insights.py#3]
I need test app on TV,but the device doesn't have sdcard slot，so I modify `DEVICE_LOG_BASE = '/sdcard/io.appetizer/'` to `DEVICE_LOG_BASE = '/data/misc/konka/io.appetizer/'`,and chmod 777 `io.appetizer`.
after install the processed apk, it doesn't log into the dir, and continuously print `D/io.appetizer: no permission, still save into memory` on  logcat.

ps: I reset `DEVICE_LOG_BASE = '/sdcard/io.appetizer/'` and use U Disk it doesn't work either

**Comment by mingyuan-xia** [comment]
`/sdcard` points to the root directory for the external storage, not necessary a physical sdcard. The instrumented/processed APK logs to `/sdcard` and then `insights.py` fetches from there. So changing `insights.py` alone will not help.
A few things to try:
1. use `adb shell`, check if `/sdcard/` exists and is writable from the shell commandline. If yes, then the current processed APK should be able to use that folder for logging. If not, we need to find another folder that is writable from the app and readable from the shell commandline.
2. check if the app has been granted `WRITE_EXTERNAL_STORAGE` permission, in the `Settings -> Apps -> <your_app> -> Permission`. If `/sdcard/` is fine and the permission is granted, then rerun the processed APK and the `no permission` line should be gone.
3. check for logcat log lines tagged with `MAGICBOOK`. Some example problematic information:
```
FileBackedLogger: external storage not available
FileBackedLogger: external storage not mounted writable
FileBackedLogger: app does not have WRITE_EXTERNAL_STORAGE permission
FileBackedLogger: app does not have READ_EXTERNAL_STORAGE permission
FileBackedLogger: sideload log dir exists but not dir
FileBackedLogger: failed to create sideload log dir
```

**Comment by mingyuan-xia** [comment]
私有化部署Appetizer可定制这部分插桩细节
logging directory and other configurations specified to instrumentation is available for private deployment version of Appetizer
