### ISSUE TITLE
win10 py2和py3 双版本 不支持么？

### ISSUE THREAD

**Issue by Archer456** [appetizerio/insights.py#4]
![image](https://user-images.githubusercontent.com/18392901/30900334-415c8582-a396-11e7-8efc-5d35c4f690b4.png)
见上图，用的是py3 `安装的依赖，但是执行
`
D:\Appetizer\insights.py>python3 insights.py
  File "insights.py", line 119
    packer = None`
报错，求解答

**Comment by mingyuan-xia** [comment]
修复了tab的问题（第二个红框）
003805848fa78a4fc7d02a85947e166ea57e3c39

关于找不到以来的问题，第一个红框里 `python3 -m pip` 在python3的环境安装了依赖，还需要 `python2 -m pip`同样做一遍，在python2的环境里面同样安装依赖。这样之后 `python3 insights.py -h`和 `python2 insights.py -h`就都可以运行了，我会把这个写到travis 测试脚本里

**Comment by Archer456** [comment]
![image](https://user-images.githubusercontent.com/18392901/30900784-d0f1a62c-a397-11e7-8bd6-9eb5a2142d9b.png)
我自己 看了下错误 看到了 这行 
`D:\Appetizer\insights.py>python3 insights.py -h
  File "insights.py", line 119
    packer = None
                ^
TabError: inconsistent use of tabs and spaces in indentation`
是tab 键和空格 在win环境下的问题 ，我用git bash 自己都处理 就好了 
@mingyuan-xia     谢谢你的回复

**Comment by mingyuan-xia** [comment]
python2/3都支持的，你pull一下，tab问题就修复了
你截图里面没有为python2安装依赖

**Comment by Archer456** [comment]
@mingyuan-xia   嗯，是的 我打算一直用python3  所以没有执行  python2 -m pip install -r requirements.txt

我用python3 没问题吧？  支持度可以吧？

**Comment by mingyuan-xia** [comment]
可以

**Comment by mingyuan-xia** [comment]
https://testerhome.com/topics/10290
楼主总结的接入经验
