### ISSUE TITLE
可以支持下载分析报告？

### ISSUE THREAD

**Issue by rubyvirus** [appetizerio/insights.py#7]
现在自动化集成过程，就差不能下载报告，可以支持吗？

**Comment by mingyuan-xia** [comment]
完成分析后有三个url是报告的三种导出格式 直接可以下载

**Comment by mingyuan-xia** [comment]
https://github.com/appetizerio/insights.py#%E4%B8%8A%E4%BC%A0log%E8%8E%B7%E5%8F%96%E5%88%86%E6%9E%90%E6%8A%A5%E5%91%8A
